
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/home/caelan/.local/lib/python3.10/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/bin/"
      - "/home/caelan/.local/bin/"
      - "/home/caelan/bin/"
      - "/usr/local/cuda/bin/"
      - "/home/caelan/.vscode-server/bin/8b640eef5a6c6089c029249d48efa5c99adf7d51/bin/remote-cli/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Users/zhouj/AppData/Local/Programs/Microsoft VS Code/"
      - "/mnt/c/Python314/Scripts/"
      - "/mnt/c/Python314/"
      - "/mnt/c/VulkanSDK/1.4.328.1/Bin/"
      - "/mnt/c/Python313/Scripts/"
      - "/mnt/c/Python313/"
      - "/mnt/c/Windows/system32/"
      - "/mnt/c/Windows/"
      - "/mnt/c/Windows/System32/Wbem/"
      - "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/Windows/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/Users/zhouj/Downloads/instantclient-basic-windows.x64-23.26.1.0.0/instantclient_23_0/"
      - "/mnt/c/Users/zhouj/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/zhouj/AppData/Roaming/npm/"
      - "/snap/bin/"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/bin"
        - "/home/caelan/.local/bin"
        - "/home/caelan/bin"
        - "/usr/local/cuda/bin"
        - "/home/caelan/.local/bin"
        - "/home/caelan/bin"
        - "/home/caelan/.vscode-server/bin/8b640eef5a6c6089c029249d48efa5c99adf7d51/bin/remote-cli"
        - "/home/caelan/.local/bin"
        - "/home/caelan/bin"
        - "/usr/local/cuda/bin"
        - "/home/caelan/.local/bin"
        - "/home/caelan/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Users/zhouj/AppData/Local/Programs/Microsoft VS Code"
        - "/mnt/c/Python314/Scripts/"
        - "/mnt/c/Python314/"
        - "/mnt/c/VulkanSDK/1.4.328.1/Bin"
        - "/mnt/c/Python313/Scripts/"
        - "/mnt/c/Python313/"
        - "/mnt/c/Windows/system32"
        - "/mnt/c/Windows"
        - "/mnt/c/Windows/System32/Wbem"
        - "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/Windows/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/"
        - "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/nodejs/"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Users/zhouj/Downloads/instantclient-basic-windows.x64-23.26.1.0.0/instantclient_23_0"
        - "/mnt/c/Python314/Scripts/"
        - "/mnt/c/Python314/"
        - "/mnt/c/VulkanSDK/1.4.328.1/Bin"
        - "/mnt/c/Python313/Scripts/"
        - "/mnt/c/Python313/"
        - "/mnt/c/Windows/system32"
        - "/mnt/c/Windows"
        - "/mnt/c/Windows/System32/Wbem"
        - "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/Windows/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/"
        - "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/nodejs/"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Users/zhouj/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/zhouj/AppData/Roaming/npm"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/home/caelan/.local/lib/python3.10/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
...
